//! The marker that makes a rendered file self-describing.
//!
//! One line, at the top of the file, carrying both halves of the ownership
//! question:
//!
//! ```markdown
//! <!-- vibe:generated v1 hash=b3:1f9a…c4 -->
//! ```
//!
//! **Ownership** is "this file begins with our marker". **Integrity** is "the
//! rest of it hashes to what the marker says". Together they answer *did we
//! write this* and *has it changed since* with nothing but the file — no
//! sidecar record, no version gate on a third on-disk format, and no table for
//! what to do when the sidecar and the file disagree. It also survives the file
//! being copied, moved, or restored from a backup, which a sidecar does not.
//!
//! That is the deliberate contrast with [`crate::agents::lock`]. An installed
//! agent's ownership *cannot* live in the file, because the file is the user's
//! to edit and must stay byte-identical to upstream — so it needs the lockfile.
//! A rendered file is ours in full, so it can carry its own proof. Same
//! question, different mechanism, for a reason (ADR-0006 Context, ADR-0007 §2).

use crate::agents::lock::{content_hash, hash_is_verifiable};

/// The marker format version. **Not** the schema version and not the template
/// version — it exists so the marker's own shape can change without every
/// previously rendered file becoming unreadable.
pub const MARKER_VERSION: u16 = 1;

const OPEN: &str = "<!-- vibe:generated v";
const HASH_KEY: &str = "hash=";
const CLOSE: &str = "-->";

/// What a file on disk is, as far as `render` is concerned.
///
/// Five states rather than three, and the two extra ones are the same two that
/// ADR-0006 §5 needed: a thing we did not write is not a modified copy of ours,
/// and a thing we cannot verify is not a thing we know differs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum RenderState {
    /// No file yet.
    Absent,
    /// Ours, and unchanged since we wrote it.
    Generated,
    /// Ours, and edited since. The edit is not derivable from the manifest, so
    /// regenerating destroys it.
    Modified,
    /// A file with no marker of ours. **Never** adopted, whatever flag is
    /// passed.
    Foreign,
    /// Our marker, carrying a claim this build cannot evaluate — an
    /// unrecognised hash algorithm, or a newer marker version.
    Unverifiable,
}

impl RenderState {
    /// Whether `render` may write over what is there.
    ///
    /// The single place the rule lives. Note the asymmetry that makes
    /// `README.md` safe to have as a target at all: **`force` does not move
    /// `Foreign`.** `--force` means "discard my edits to *your* file"; it is
    /// not a way to claim a file `vibe` never wrote. Same rule as
    /// `PresentUnowned` in ADR-0006 §5, which `--force` also does not override.
    #[must_use]
    pub fn may_overwrite(self, force: bool) -> bool {
        match self {
            RenderState::Absent | RenderState::Generated => true,
            RenderState::Modified | RenderState::Unverifiable => force,
            RenderState::Foreign => false,
        }
    }

    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            RenderState::Absent => "absent",
            RenderState::Generated => "generated",
            RenderState::Modified => "modified",
            RenderState::Foreign => "not generated by vibe",
            RenderState::Unverifiable => "unverifiable",
        }
    }
}

/// Normalise the bytes a hash is taken over.
///
/// Line endings collapse to `\n` and trailing whitespace at end-of-file is
/// dropped. **This is not tidiness.** `git` rewrites line endings on checkout
/// under `core.autocrlf`, which is the default on Windows, so a hash over raw
/// bytes would break on the next clone and report *every rendered file in the
/// repository* as modified — offering to overwrite work nobody touched, on a
/// machine that did nothing wrong.
///
/// It normalises exactly the two things a checkout or an editor-on-save does,
/// and nothing else: a content change of any kind still changes the hash.
fn normalise(body: &str) -> String {
    let mut out = body.replace("\r\n", "\n").replace('\r', "\n");
    while out.ends_with(['\n', ' ', '\t']) {
        out.pop();
    }
    out
}

/// Render the marker line for a body.
#[must_use]
pub fn line_for(body: &str) -> String {
    format!(
        "{OPEN}{MARKER_VERSION} {HASH_KEY}{} {CLOSE}",
        content_hash(normalise(body).as_bytes())
    )
}

/// A body plus its marker: exactly what `render` writes to disk.
#[must_use]
pub fn wrap(body: &str) -> String {
    let body = body.strip_prefix('\n').unwrap_or(body);
    format!("{}\n{body}", line_for(body))
}

/// The parsed marker, if the first line is one of ours.
struct Marker {
    version: u16,
    hash: String,
}

fn parse_first_line(file: &str) -> Option<Marker> {
    // The *first* line, deliberately. A marker further down would let a
    // generated example quoted inside somebody's hand-written prose claim the
    // whole file.
    let first = file.lines().next()?.trim();
    let rest = first.strip_prefix(OPEN)?.strip_suffix(CLOSE)?.trim_end();
    let (version, rest) = rest.split_once(' ')?;
    Some(Marker {
        // An unparseable version is still *our* marker, so it must not read as
        // Foreign. It is reported as a version we cannot evaluate.
        version: version.trim().parse().unwrap_or(u16::MAX),
        hash: rest.trim().strip_prefix(HASH_KEY)?.trim().to_owned(),
    })
}

/// Everything after the marker line, or `None` if there is no marker.
#[must_use]
pub fn body_of(file: &str) -> Option<String> {
    parse_first_line(file)?;
    let rest = file.split_once('\n').map_or("", |(_, rest)| rest);
    Some(rest.to_owned())
}

/// Decide what a file on disk is.
#[must_use]
pub fn classify(file: &str) -> RenderState {
    let Some(marker) = parse_first_line(file) else {
        return RenderState::Foreign;
    };
    // Our marker, from a build that writes a shape this one does not know. Not
    // Foreign — ownership is established — but nothing after `v9` is a claim
    // this build can evaluate.
    if marker.version != MARKER_VERSION {
        return RenderState::Unverifiable;
    }
    // A hash we cannot recompute. "Cannot tell" is not "differs" (ADR-0006 §3).
    if !hash_is_verifiable(&marker.hash) {
        return RenderState::Unverifiable;
    }

    let body = file.split_once('\n').map_or("", |(_, rest)| rest);
    if content_hash(normalise(body).as_bytes()) == marker.hash {
        RenderState::Generated
    } else {
        RenderState::Modified
    }
}

/// Classify a file that may not exist.
#[must_use]
pub fn classify_path(path: &std::path::Path) -> RenderState {
    match std::fs::read_to_string(path) {
        Ok(text) => classify(&text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => RenderState::Absent,
        // Unreadable is not absent, and writing over it would be a guess about
        // a file we could not look at.
        Err(_) => RenderState::Unverifiable,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalise_collapses_only_line_endings_and_trailing_space() {
        assert_eq!(normalise("a\r\nb\r\n"), "a\nb");
        assert_eq!(normalise("a\nb\n\n\n"), "a\nb");
        assert_eq!(normalise("a\rb"), "a\nb");
        // And nothing else: interior whitespace is content.
        assert_eq!(normalise("a  b\n"), "a  b");
        assert_ne!(normalise("a\nb"), normalise("a\nc"));
    }

    #[test]
    fn a_marker_without_a_hash_key_is_not_a_marker() {
        assert_eq!(
            classify("<!-- vibe:generated v1 -->\nbody\n"),
            RenderState::Foreign
        );
        assert_eq!(classify("<!-- vibe:generated -->\n"), RenderState::Foreign);
    }

    #[test]
    fn a_marker_with_an_unparseable_version_is_unverifiable_not_foreign() {
        assert_eq!(
            classify("<!-- vibe:generated vX hash=b3:aa -->\nbody\n"),
            RenderState::Unverifiable
        );
    }

    #[test]
    fn wrap_then_classify_round_trips_for_bodies_that_need_care() {
        for body in [
            "",
            "\n",
            "# heading\n",
            "text with <!-- a comment --> inside\n",
            "a body mentioning vibe:generated in prose\n",
            "trailing spaces   \n",
        ] {
            assert_eq!(
                classify(&wrap(body)),
                RenderState::Generated,
                "body {body:?} did not round-trip"
            );
        }
    }

    #[test]
    fn absent_is_not_foreign() {
        let dir = tempfile::tempdir().unwrap();
        // The distinction that decides whether `render` writes at all: no file
        // is a thing to create, not a thing that belongs to someone else.
        assert_eq!(
            classify_path(&dir.path().join("CLAUDE.md")),
            RenderState::Absent
        );
        assert!(RenderState::Absent.may_overwrite(false));
    }
}
